# Generated by Django 3.2.7 on 2021-09-27 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='attendess',
            new_name='attendees',
        ),
        migrations.AlterField(
            model_name='venue',
            name='phone',
            field=models.CharField(max_length=25, verbose_name='Contact Phone'),
        ),
    ]
